object DependenciesVersions {
    const val CORE_KTX = "1.10.1"
    const val LIFECYCLE_RUNTIME_KTX = "2.8.7"
    const val ACTIVITY_COMPOSE = "1.10.1"
    const val COMPOSE_BOM = "2024.04.01"
    const val JUNIT = "4.13.2"
    const val JUNIT_VERSION = "1.2.1"
    const val ESPRESSO_CORE = "3.5.1"
    const val NAVIGATION_COMPOSE = "2.8.9"
    const val ROOM = "2.6.1"
    const val GSON = "2.12.1"
    const val KOIN = "4.0.2"
    const val INDICATOR = "0.0.8"
    const val DATASTORE = "1.1.3"
    const val LOTTIE = "6.6.4"
    const val KTOR = "3.1.1"
}